apiVersion: v1
kind: ServiceAccount
metadata:
  name: policyengine
  namespace: poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-reader
rules:
  - apiGroups: ["policy.poc.io"]
    resources: ["policies"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policyengine-policy-reader
subjects:
  - kind: ServiceAccount
    name: policyengine
    namespace: poc
roleRef:
  kind: ClusterRole
  name: policy-reader
  apiGroup: rbac.authorization.k8s.io
